import { db } from '../services/db';

const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.sales': 'Sales',
    'nav.purchases': 'Purchases',
    'nav.products': 'Products',
    'nav.all_items': 'All Items',
    'nav.storage': 'Storage',
    'nav.new_invoice': 'New Invoice',
    'nav.invoices': 'Invoices',
    'nav.inventory': 'Inventory',
    'nav.inventory_analysis': 'Advanced Analysis',
    'nav.customers': 'Customers',
    'nav.suppliers': 'Suppliers',
    'nav.representatives': 'Representatives',
    'nav.warehouses': 'Warehouses',
    'nav.cash': 'Cash Register',
    'nav.settings': 'Settings',
    'nav.reports': 'Reports & Analytics',
    'nav.shortages': 'Shortages & Alerts',
    'nav.reports_sales': 'Sales Reports',
    'nav.reports_purchases': 'Purchase Reports',
    'nav.reports_reps': 'Representatives Reports',
    'nav.user_management': 'User Management',
    'nav.telesales': 'Telesales',
    
    // General App
    'app.name': 'Mizan Online',
    'app.admin': 'Administrator',
    'app.overview': 'Overview',
    
    // Dashboard
    'dash.total_sales': 'Total Sales',
    'dash.cash_balance': 'Cash Balance',
    'dash.customers': 'Customers',
    'dash.low_stock': 'Low Stock',
    'dash.sales_trend': 'Sales Trend (7 Days)',
    'dash.inventory_health': 'Inventory Health',
    'dash.quick_actions': 'Quick Actions',
    'dash.supplier_stmt': 'Supplier Statement',
    'dash.insights': 'Insights & Reports',
    'dash.insights_desc': 'Access detailed financial statements, profit & loss analysis, and inventory valuation reports.',
    'dash.view_reports': 'View Reports',

    // Inventory
    'stock.title': 'Inventory Management',
    'stock.import': 'Import Excel',
    'stock.new': '+ Quick Item',
    'stock.purchase': 'Purchase Invoice',
    'stock.order': 'Purchase Order',
    'stock.order_history': 'Order History',
    'stock.return': 'Return Invoice',
    'stock.total': 'Total Stock',
    'stock.batch': 'Batch',
    'stock.expiry': 'Expiry',
    'stock.price': 'Price',
    'stock.cost': 'Cost',
    'stock.qty': 'Qty',
    'stock.active': 'ACTIVE',
    'stock.expired': 'EXPIRED',
    'stock.warehouse': 'Warehouse',
    'stock.transfer': 'Transfer Stock',
    'stock.transfer_title': 'Transfer Between Warehouses',
    'stock.to_warehouse': 'To Warehouse',
    'stock.transfer_qty': 'Transfer Qty',
    'stock.inventory_count': 'Stock Take',
    'stock.card_item': 'Card Item (Movement History)',
    'stock.hist_type': 'Type',
    'stock.hist_in_out': 'In/Out',
    'stock.hist_ref': 'Ref/Note',
    'stock.spoilage': 'Report Spoilage',
    'stock.actual_qty': 'Actual Count',
    'stock.damaged_qty': 'Damaged Qty',
    'stock.reason': 'Reason / Note',
    'stock.adjust': 'Adjust Stock',
    'stock.confirm_spoilage': 'Confirm Damage',
    'stock.avail': 'Avail',
    'stock.source': 'Source',
    'stock.confirm_transfer': 'Confirm Transfer',
    'stock.spoilage_desc': 'Reporting damaged goods will permanently remove them from stock. This action cannot be undone.',
    
    // Stock Take Tab
    'stock.tab_overview': 'Stock Overview',
    'stock.tab_take': 'Stock Take (Count)',
    'stock.take_mode': 'Bulk Stock Take Mode',
    'stock.sys_qty': 'System Qty',
    'stock.diff': 'Diff',
    'stock.save_adjustments': 'Save Adjustments',
    'stock.no_changes': 'No changes detected',
    
    // Warehouses
    'ware.title': 'Warehouse Management',
    'ware.add': 'Add Warehouse',
    'ware.name': 'Warehouse Name',
    'ware.type': 'Type',
    'ware.default': 'Main Store',
    'ware.sub': 'Sub Store',
    
    // Customers & Suppliers
    'cust.title': 'Customers',
    'cust.add': 'Add Customer',
    'cust.search': 'Search...',
    'cust.code': 'Code',
    'cust.name': 'Name',
    'cust.phone': 'Phone',
    'cust.balance': 'Balance',
    'cust.rep': 'Representative',
    'cust.statement': 'Customer Statement',
    'cust.tab_list': 'Customers List',
    'cust.tab_analysis': 'Analysis & Metrics',
    'cust.repayment_ratio': 'Repayment %',
    'cust.total_sales': 'Total Sales',
    'cust.total_paid': 'Total Paid',
    'cust.inv_count': 'Inv. Count',
    'cust.monthly_rate': 'Monthly Rate',
    'cust.export_excel': 'Export Excel',
    'cust.export_pdf': 'Export PDF',
    'cust.default_discount': 'Fixed Discount %',
    'cust.address': 'Address',
    'cust.dist_line': 'Distribution Line',
    'supp.title': 'Suppliers',
    'supp.add': 'Add Supplier',
    'supp.contact': 'Contact Person',
    
    // Representatives
    'rep.title': 'Representatives',
    'rep.add': 'Add Rep',
    'rep.code': 'Rep Code',
    'rep.name': 'Rep Name',
    'rep.customers_count': 'Assigned Customers',
    'rep.commission': 'Commission Rate (%)',
    'rep.target': 'Sales Target',
    'rep.commission_amount': 'Commission Amount',
    'rep.daily_closing': 'Daily Closing',
    'rep.select_rep': 'Select Representative',
    'rep.invoices_today': 'Invoices Today',
    'rep.total_collected': 'Total Collected',
    'rep.total_remaining': 'Pending Amount',
    'rep.collect': 'Collect',
    'rep.partial': 'Partial',
    'rep.full': 'Paid',
    'rep.print_manifest': 'Print Loading Sheet',
    'rep.manifest_title': 'Delivery Manifest / Loading Sheet',
    'rep.driver_sig': 'Receiver Signature',
    
    // Cash Register
    'cash.title': 'Cash Register',
    'cash.receipt': 'Receipt',
    'cash.expense': 'Expense',
    'cash.history': 'History',
    'cash.category': 'Category',
    'cash.entity': 'Account/Name',
    'cash.income': 'Total Income',
    'cash.total_expenses': 'Total Expenses',
    'cash.net': 'Net Cash',
    'cash.date': 'Date',
    'cat.CUSTOMER_PAYMENT': 'Customer Payment',
    'cat.PARTNER_CONTRIBUTION': 'Partner Contribution',
    'cat.SUPPLIER_PAYMENT': 'Supplier Payment',
    'cat.SALARY': 'Salaries',
    'cat.ELECTRICITY': 'Electricity',
    'cat.MARKETING': 'Marketing',
    'cat.OTHER': 'Other',
    
    // Settings
    'set.title': 'Settings',
    'set.language': 'Language',
    'set.currency': 'Currency',
    'set.save': 'Save Changes',
    'set.reset': 'Reset Database',
    'set.tab_general': 'General',
    'set.tab_invoice': 'Invoice Design',
    'set.tab_users': 'Users & Permissions',
    'set.tab_printer': 'Printer Settings',
    'set.paper_size': 'Paper Size',
    'set.paper_a4': 'A4 (Standard)',
    'set.paper_a5': 'A5 (Half)',
    'set.paper_thermal': 'Thermal (Receipt)',
    'set.company_info': 'Company Information',
    'set.company_name': 'Company Name',
    'set.tax_no': 'Tax Number / Reg ID',
    'set.phone': 'Phone Number',
    'set.address': 'Address',
    'set.sys_pref': 'System Preferences',
    'set.select_template': 'Select Invoice Template',
    'set.low_stock_threshold': 'Low Stock Threshold',
    'set.backup_mgmt': 'Database Management',
    'set.backup_desc': 'Backup your data regularly to prevent loss.',
    'set.export_data': 'Export Data (Backup)',
    'set.export_desc': 'Download a complete JSON file of all your invoices, customers, and inventory.',
    'set.download_backup': 'Download Backup',
    'set.import_data': 'Import Data (Restore)',
    'set.import_desc': 'Restore data from a backup file. Warning: This overwrites current data.',
    'set.select_file': 'Select File',
    'set.danger_zone': 'Danger Zone',
    'set.danger_desc': 'These actions are destructive and cannot be undone. Please be careful.',
    'set.clear_trans': 'Reset Transactions',
    'set.clear_trans_desc': 'Deletes all Invoices, Purchases, and Cash transactions. Resets Customer/Supplier balances.',
    'set.delete_trans': 'Delete Transactions',
    'set.clear_cust': 'Delete Customers',
    'set.clear_cust_desc': 'Permanently deletes the entire customer database.',
    'set.delete_cust': 'Delete All Customers',
    'set.clear_prod': 'Delete Products',
    'set.clear_prod_desc': 'Permanently deletes all Products, Batches, and Stock data.',
    'set.delete_prod': 'Delete All Products',
    'set.factory_reset': 'Factory Reset',
    'set.factory_desc': 'Wipes the entire database including Settings, Users, and all Data.',
    'set.reset_everything': 'RESET EVERYTHING',

    // User Management
    'user.mgmt_title': 'User Management',
    'user.add': 'Add User',
    'user.edit': 'Edit User',
    'user.fullname': 'Full Name',
    'user.username': 'Username',
    'user.password': 'Password',
    'user.role': 'Role',
    'user.permissions': 'System Permissions',
    'user.save': 'Save User',
    'user.delete_confirm': 'Are you sure you want to delete this user?',
    'role.admin': 'Administrator',
    'role.user': 'User (Employee)',
    'perm.VIEW_DASHBOARD': 'View Dashboard',
    'perm.VIEW_REPORTS': 'View Reports',
    'perm.MANAGE_SALES': 'Manage Sales (Invoices)',
    'perm.MANAGE_INVENTORY': 'Manage Inventory',
    'perm.MANAGE_STOCK_TAKE': 'Perform Stock Take',
    'perm.MANAGE_CUSTOMERS': 'Manage Customers',
    'perm.MANAGE_SUPPLIERS': 'Manage Suppliers',
    'perm.MANAGE_REPS': 'Manage Representatives',
    'perm.MANAGE_WAREHOUSES': 'Manage Warehouses',
    'perm.MANAGE_CASH': 'Cash Register Access',
    'perm.MANAGE_SETTINGS': 'System Settings',
    'perm.MANAGE_USERS': 'Manage Users',
    
    // Invoices & Sales
    'inv.add': 'Add Product',
    'inv.add_product': 'Add Product',
    'inv.customer': 'Customer',
    'inv.supplier': 'Supplier',
    'inv.total': 'Total',
    'inv.subtotal': 'Subtotal',
    'inv.discount': 'Discount',
    'inv.additional_discount': 'Extra Discount',
    'inv.net_total': 'Net Invoice',
    'inv.prev_balance': 'Previous Balance',
    'inv.grand_total': 'Total Due',
    'inv.cash_paid': 'Cash Paid',
    'inv.new_balance': 'New Balance',
    'inv.processing': 'Processing...',
    'inv.finalize': 'Finalize Invoice',
    'inv.update': 'Update Invoice',
    'inv.save_print': 'Save & Print',
    'inv.product': 'Product',
    'inv.batch': 'Batch',
    'inv.qty': 'Qty',
    'inv.bonus': 'Bonus',
    'inv.price': 'Price',
    'inv.action': 'Action',
    'inv.empty_cart': 'Cart is empty',
    'inv.select_customer': 'Select Customer',
    'inv.select_product': 'Select Product',
    'inv.select_batch': 'Select Batch',
    'inv.add_btn': 'Add',
    'inv.insufficient_stock': 'Insufficient Stock',
    'inv.details': 'Invoice Details',
    'inv.select_warehouse': 'Select Warehouse',
    'inv.profit': 'Profit',
    'inv.security_warning': 'Security Warning',
    'inv.below_cost_desc': 'You are attempting to sell an item below its cost price. This action requires Administrator approval.',
    'inv.selling_net': 'Selling Price (Net)',
    'inv.admin_pass_prompt': 'Admin Password',
    'inv.approve': 'Approve Sale',
    'inv.wrong_pass': 'Incorrect Admin Password',
    'inv.return_mode': 'Return Mode',
    'inv.returns_active': 'Returns Active',
    'inv.sales_return': 'Sales Return',
    'inv.total_items': 'Total Items',
    'inv.add_return_item': 'Add Return Item',
    'inv.manual_price': 'Manual Price',
    'inv.save_off_public': 'Save {percent}% off Public',
    'inv.disc_percent': 'Disc %',
    'inv.return_summary': 'Return Summary',
    'inv.payment_summary': 'Payment Summary',
    'inv.cash_refunded': 'Cash Refunded',
    'inv.process_return': 'Process Return',
    'inv.settings': 'Invoice Settings',
    'inv.standard_pricing': 'Standard Pricing',
    'inv.standard_desc': 'Fixed batch price + Discount %',
    'inv.manual_price_only': 'Manual Price Only',
    'inv.manual_desc': 'Enter price manually. No discount.',
    'inv.profit_view': 'Profit View',
    'inv.profit_desc': 'Manual price + Discount. Show Cost & Public price.',

    // Purchasing
    'pur.title': 'New Purchase Invoice',
    'pur.return_title': 'Purchase Return',
    'pur.list_title': 'Purchase Log',
    'pur.select_supplier': 'Select Supplier',
    'pur.cost': 'Cost Price',
    'pur.sell': 'Selling Price',
    'pur.batch': 'Batch No',
    'pur.expiry': 'Expiry Date',
    'pur.add_item': 'Add Item',
    'pur.submit': 'Save Purchase',
    'pur.return_submit': 'Save Return',
    'pur.new_order': 'New Order',
    'pur.order_summary': 'Order Summary',
    'pur.add_to_order': 'Add items to order',
    'pur.save_order_log': 'Save Order Log',
    'pur.items_count': 'Items Count',
    'pur.receive': 'Receive / Review',
    'pur.review_order': 'Review Order & Receive',
    'pur.convert_invoice': 'Confirm Receipt & Create Invoice',
    'pur.convert_success': 'Order successfully converted to Purchase Invoice!',
    'pur.type': 'Type',
    'pur.invoice_no': 'Invoice #',
    'pur.total_amount': 'Total',
    'pur.paid_amount': 'Paid',

    // Product
    'prod.new_title': 'Add New Product',
    'prod.name': 'Product Name',
    'prod.code': 'Code / Barcode',
    'prod.pkg_type': 'Package Type',
    'prod.pkg_items': 'Items per Pkg',
    
    // Lists & Common
    'list.title': 'Invoices List',
    'list.search': 'Search Invoice No...',
    'list.status': 'Status',
    'list.view': 'View',
    'list.edit': 'Edit',
    'list.no_data': 'No data found',
    'common.date': 'Date',
    'common.customer': 'Customer',
    'common.user': 'User',
    'common.status': 'Status',
    'common.action': 'Action',
    'common.success_import': 'Import Successful',
    'common.error_excel': 'Error reading file',
    'common.statement': 'Account Statement',
    'common.debit': 'Debit',
    'common.credit': 'Credit',
    'common.balance': 'Balance',
    'common.desc': 'Description',
    'common.opening': 'Opening Balance',
    'common.print': 'Print',
    'common.landscape': 'Landscape',
    'common.thermal': 'Thermal',
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.show': 'Show',
    'common.items': 'Items',
    'status.paid': 'Paid',
    'status.partial': 'Partial',
    'status.unpaid': 'Unpaid',
    
    // Reports
    'rep.period': 'Time Period',
    'rep.from': 'From',
    'rep.to': 'To',
    'rep.apply': 'Apply Filter',
    'rep.today': 'Today',
    'rep.this_month': 'This Month',
    'rep.last_month': 'Last Month',
    'rep.this_year': 'This Year',
    'rep.tab.financial': 'Financial (P&L)',
    'rep.tab.sales': 'Sales Analysis',
    'rep.tab.purchases': 'Purchase Analysis',
    'rep.tab.inventory': 'Inventory Value',
    'rep.tab.partners': 'Partners & Debt',
    'rep.tab.reps': 'Representatives',
    'rep.tab.telesales': 'Telesales Performance',
    'rep.tab.monthly': 'Monthly Summary',
    'rep.tab.shortages': 'Shortages',
    'rep.gross_profit': 'Gross Profit',
    'rep.net_profit': 'Net Profit',
    'rep.total_revenue': 'Total Revenue',
    'rep.cogs': 'Cost of Goods Sold',
    'rep.expenses': 'Operating Expenses',
    'rep.stock_value': 'Stock Asset Value',
    'rep.receivables': 'Receivables (Customers)',
    'rep.payables': 'Payables (Suppliers)',
    'rep.area': 'Area / Region',
    'rep.all_customers': 'All Customers',
    'rep.all_areas': 'All Areas',
    'rep.product_breakdown': 'Product Sales Breakdown',
    'rep.units': 'Units',
    'rep.sales_volume': 'Sales Volume',
    'rep.invoice_count': 'Invoice Count',
    'rep.active_customers': 'Active Customers',
    'rep.commission_est': 'Est. Commission (1%)',
    'rep.all_reps': 'All Representatives',
    'rep.item_details': 'Item Sales Details',
    'rep.short.daily': 'Daily Sales Shortages',
    'rep.short.general': 'General Low Stock',
    'rep.short.stagnant': 'Stagnant (No Sales)',
    'rep.short.sold_today_list': 'Sold Today',
    'rep.short.best_selling': 'Best Selling',
    'rep.short.current': 'Current Stock',
    'rep.short.sold_today': 'Sold Today',
    'rep.short.total_sold': 'Total Sold',
    'rep.short.status': 'Status',
    'rep.short.out_of_stock': 'Out of Stock',
    'rep.short.low_stock': 'Low Stock',
    'rep.last_cost_1': 'Last Cost 1',
    'rep.last_cost_2': 'Last Cost 2',
    'rep.monthly_avg': 'Mo. Avg',
    'rep.short.show_top': 'Show Top',
    'rep.short.show_all': 'Show All',
    'rep.agent': 'Agent Name',
    'rep.orders_count': 'Orders Count',
    'rep.total_value': 'Total Value',
    'rep.details': 'Details',
    'rep.mon.sales': 'Sales (Revenue)',
    'rep.mon.cash': 'Cash In',
    'rep.mon.purchases': 'Purchases',
    'rep.mon.expenses': 'Expenses',
    'rep.mon.credit': 'Unpaid Sales',
    'rep.mon.select': 'Select Month',
    
    // Analysis
    'analysis.title': 'Advanced Inventory Analysis',
    'analysis.abc_title': 'ABC Classification (Pareto)',
    'analysis.valuation_title': 'Valuation & Weighted Avg Cost',
    'analysis.class_a': 'Class A (High Value)',
    'analysis.class_b': 'Class B (Medium)',
    'analysis.class_c': 'Class C (Low Value)',
    'analysis.wac': 'Weighted Avg Cost',
    'analysis.total_asset': 'Total Asset Value',
    'analysis.turnover': 'Est. Turnover Rate',
    'analysis.revenue_share': 'Revenue Share',
    'analysis.optimize': 'Optimize stock levels using ABC classification and valuation metrics.',
    'analysis.latest_cost': 'Latest Cost'
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.sales': 'المبيعات',
    'nav.purchases': 'المشتريات',
    'nav.products': 'المنتجات',
    'nav.all_items': 'كل الأصناف',
    'nav.storage': 'المخازن',
    'nav.new_invoice': 'فاتورة بيع',
    'nav.invoices': 'سجل المبيعات',
    'nav.inventory': 'المخزون',
    'nav.inventory_analysis': 'تحليل المخزون',
    'nav.customers': 'العملاء',
    'nav.suppliers': 'الموردين',
    'nav.representatives': 'المندوبين',
    'nav.warehouses': 'المخازن',
    'nav.cash': 'الخزينة',
    'nav.settings': 'الإعدادات',
    'nav.reports': 'التقارير والتحليلات',
    'nav.shortages': 'النواقص والتنبيهات', 
    'nav.reports_sales': 'تقارير المبيعات',
    'nav.reports_purchases': 'تقارير المشتريات',
    'nav.reports_reps': 'تقارير المندوبين',
    'nav.user_management': 'إدارة المستخدمين',
    'nav.telesales': 'التيليسيلز',
    
    // General App
    'app.name': 'ميزان أونلاين',
    'app.admin': 'مدير النظام',
    'app.overview': 'نظرة عامة',
    
    // Dashboard
    'dash.total_sales': 'إجمالي المبيعات',
    'dash.cash_balance': 'رصيد الخزينة',
    'dash.customers': 'عدد العملاء',
    'dash.low_stock': 'نواقص المخزون',
    'dash.sales_trend': 'مؤشر المبيعات (٧ أيام)',
    'dash.inventory_health': 'حالة المخزون',
    'dash.quick_actions': 'إجراءات سريعة',
    'dash.supplier_stmt': 'كشف حساب مورد',
    'dash.insights': 'رؤى وتقارير',
    'dash.insights_desc': 'الوصول إلى القوائم المالية التفصيلية، تحليل الأرباح والخسائر، وتقارير تقييم المخزون.',
    'dash.view_reports': 'عرض التقارير',

    // Inventory
    'stock.title': 'إدارة المخزون',
    'stock.import': 'استيراد إكسيل',
    'stock.new': '+ صنف سريع',
    'stock.purchase': 'فاتورة مشتريات',
    'stock.order': 'طلب شراء',
    'stock.order_history': 'سجل الطلبات',
    'stock.return': 'فاتورة مرتجع',
    'stock.total': 'الرصيد',
    'stock.batch': 'تشغيلة',
    'stock.expiry': 'صلاحية',
    'stock.price': 'سعر بيع',
    'stock.cost': 'تكلفة',
    'stock.qty': 'كمية',
    'stock.active': 'نشط',
    'stock.expired': 'منتهي',
    'stock.warehouse': 'المخزن',
    'stock.transfer': 'تحويل مخزني',
    'stock.transfer_title': 'تحويل بين المخازن',
    'stock.to_warehouse': 'إلى مخزن',
    'stock.transfer_qty': 'الكمية المحولة',
    'stock.inventory_count': 'جرد المخزن',
    'stock.card_item': 'كارت الصنف (سجل الحركات)',
    'stock.hist_type': 'النوع',
    'stock.hist_in_out': 'وارد/صادر',
    'stock.hist_ref': 'المرجع/ملاحظات',
    'stock.spoilage': 'تبليغ توالف',
    'stock.actual_qty': 'العدد الفعلي',
    'stock.damaged_qty': 'الكمية التالفة',
    'stock.reason': 'السبب / ملاحظات',
    'stock.adjust': 'ضبط الرصيد',
    'stock.confirm_spoilage': 'خصم التوالف',
    'stock.avail': 'متاح',
    'stock.source': 'المصدر',
    'stock.confirm_transfer': 'تأكيد التحويل',
    'stock.spoilage_desc': 'تسجيل التوالف سيقوم بخصم الكمية نهائياً من المخزون. لا يمكن التراجع عن هذا الإجراء.',

    // Stock Take Tab
    'stock.tab_overview': 'سجل المخزون',
    'stock.tab_take': 'الجرد الفعلي',
    'stock.take_mode': 'وضع الجرد الجماعي',
    'stock.sys_qty': 'الرصيد دفتري',
    'stock.diff': 'الفرق',
    'stock.save_adjustments': 'حفظ تسوية الجرد',
    'stock.no_changes': 'لا توجد تغييرات للحفظ',

    // Warehouses
    'ware.title': 'إدارة المخازن',
    'ware.add': 'إضافة مخزن',
    'ware.name': 'اسم المخزن',
    'ware.type': 'النوع',
    'ware.default': 'رئيسي',
    'ware.sub': 'فرعي',
    
    // Customers & Suppliers
    'cust.title': 'العملاء',
    'cust.add': 'إضافة عميل',
    'cust.search': 'بحث...',
    'cust.code': 'كود',
    'cust.name': 'الاسم',
    'cust.phone': 'هاتف',
    'cust.balance': 'الرصيد',
    'cust.rep': 'المندوب',
    'cust.statement': 'كشف حساب',
    'cust.tab_list': 'قائمة العملاء',
    'cust.tab_analysis': 'تحليل العملاء',
    'cust.repayment_ratio': 'نسبة السداد',
    'cust.total_sales': 'إجمالي المشتريات',
    'cust.total_paid': 'إجمالي المدفوعات',
    'cust.inv_count': 'عدد الفواتير',
    'cust.monthly_rate': 'المعدل الشهري للطلبات',
    'cust.export_excel': 'تصدير إكسيل',
    'cust.export_pdf': 'تصدير PDF',
    'cust.default_discount': 'خصم ثابت %',
    'cust.address': 'العنوان',
    'cust.dist_line': 'خط التوزيع',
    'supp.title': 'الموردين',
    'supp.add': 'إضافة مورد',
    'supp.contact': 'المسئول',
    
    // Representatives
    'rep.title': 'المندوبين',
    'rep.add': 'إضافة مندوب',
    'rep.code': 'كود المندوب',
    'rep.name': 'اسم المندوب',
    'rep.customers_count': 'عدد العملاء',
    'rep.commission': 'نسبة العمولة (%)',
    'rep.target': 'هدف المبيعات (تارجت)',
    'rep.commission_amount': 'قيمة العمولة',
    'rep.daily_closing': 'تقفيل يومي',
    'rep.select_rep': 'اختر المندوب',
    'rep.invoices_today': 'فواتير اليوم',
    'rep.total_collected': 'المحصل',
    'rep.total_remaining': 'المتبقي',
    'rep.collect': 'تحصيل',
    'rep.partial': 'جزئي',
    'rep.full': 'خالص',
    'rep.print_manifest': 'طباعة منفستو',
    'rep.manifest_title': 'منفستو تسليم / كشف تحميل',
    'rep.driver_sig': 'توقيع المستلم',
    
    // Cash Register
    'cash.title': 'الخزينة',
    'cash.receipt': 'سند قبض',
    'cash.expense': 'سند صرف',
    'cash.history': 'السجل',
    'cash.category': 'البند',
    'cash.entity': 'الحساب/الاسم',
    'cash.income': 'إجمالي المقبوضات',
    'cash.total_expenses': 'إجمالي المصروفات',
    'cash.net': 'صافي النقدية',
    'cash.date': 'التاريخ',
    'cat.CUSTOMER_PAYMENT': 'تحصيل عميل',
    'cat.PARTNER_CONTRIBUTION': 'إيداع شريك',
    'cat.SUPPLIER_PAYMENT': 'سداد مورد',
    'cat.SALARY': 'رواتب',
    'cat.ELECTRICITY': 'كهرباء',
    'cat.MARKETING': 'تسويق',
    'cat.OTHER': 'نثريات',
    
    // Settings
    'set.title': 'الإعدادات',
    'set.language': 'اللغة',
    'set.currency': 'العملة',
    'set.save': 'حفظ التغييرات',
    'set.reset': 'تهيئة قاعدة البيانات',
    'set.tab_general': 'عام',
    'set.tab_invoice': 'تصميم الفاتورة',
    'set.tab_users': 'المستخدمين والصلاحيات',
    'set.tab_printer': 'إعدادات الطابعة',
    'set.paper_size': 'حجم الورق',
    'set.paper_a4': 'A4 (قياسي)',
    'set.paper_a5': 'A5 (نصفي)',
    'set.paper_thermal': 'إيصال حراري (Thermal)',
    'set.company_info': 'بيانات الشركة',
    'set.company_name': 'اسم الشركة',
    'set.tax_no': 'الرقم الضريبي / س.ت',
    'set.phone': 'رقم الهاتف',
    'set.address': 'العنوان',
    'set.sys_pref': 'تفضيلات النظام',
    'set.select_template': 'اختر شكل الفاتورة',
    'set.low_stock_threshold': 'حد النواقص (الكمية)',
    'set.backup_mgmt': 'إدارة النسخ الاحتياطي',
    'set.backup_desc': 'قم بعمل نسخ احتياطية بانتظام لتجنب فقدان البيانات.',
    'set.export_data': 'تصدير البيانات (نسخة احتياطية)',
    'set.export_desc': 'تحميل ملف JSON كامل يحتوي على جميع الفواتير والعملاء والمخزون.',
    'set.download_backup': 'تحميل النسخة',
    'set.import_data': 'استرجاع البيانات',
    'set.import_desc': 'استعادة البيانات من ملف نسخ احتياطي. تحذير: سيتم استبدال البيانات الحالية.',
    'set.select_file': 'اختر الملف',
    'set.danger_zone': 'منطقة الخطر',
    'set.danger_desc': 'هذه الإجراءات خطيرة ولا يمكن التراجع عنها. يرجى الحذر.',
    'set.clear_trans': 'تصفير الحركات',
    'set.clear_trans_desc': 'حذف جميع الفواتير والمشتريات وحركات الخزينة. تصفير أرصدة العملاء والموردين.',
    'set.delete_trans': 'حذف الحركات',
    'set.clear_cust': 'حذف العملاء',
    'set.clear_cust_desc': 'حذف قاعدة بيانات العملاء بالكامل نهائياً.',
    'set.delete_cust': 'حذف كل العملاء',
    'set.clear_prod': 'حذف الأصناف',
    'set.clear_prod_desc': 'حذف جميع المنتجات والتشغيلات وبيانات المخزون نهائياً.',
    'set.delete_prod': 'حذف كل الأصناف',
    'set.factory_reset': 'ضبط المصنع',
    'set.factory_desc': 'مسح قاعدة البيانات بالكامل بما في ذلك الإعدادات والمستخدمين وجميع البيانات.',
    'set.reset_everything': 'حذف كل شيء',

    // User Management
    'user.mgmt_title': 'إدارة المستخدمين',
    'user.add': 'إضافة مستخدم',
    'user.edit': 'تعديل مستخدم',
    'user.fullname': 'الاسم بالكامل',
    'user.username': 'اسم المستخدم',
    'user.password': 'كلمة المرور',
    'user.role': 'الصلاحية',
    'user.permissions': 'أذونات النظام',
    'user.save': 'حفظ المستخدم',
    'user.delete_confirm': 'هل أنت متأكد من حذف هذا المستخدم؟',
    'role.admin': 'مدير (Admin)',
    'role.user': 'مستخدم (موظف)',
    'perm.VIEW_DASHBOARD': 'عرض لوحة التحكم',
    'perm.VIEW_REPORTS': 'عرض التقارير',
    'perm.MANAGE_SALES': 'إدارة المبيعات (الفواتير)',
    'perm.MANAGE_INVENTORY': 'إدارة المخزون',
    'perm.MANAGE_STOCK_TAKE': 'إجراء الجرد',
    'perm.MANAGE_CUSTOMERS': 'إدارة العملاء',
    'perm.MANAGE_SUPPLIERS': 'إدارة الموردين',
    'perm.MANAGE_REPS': 'إدارة المندوبين',
    'perm.MANAGE_WAREHOUSES': 'إدارة المخازن',
    'perm.MANAGE_CASH': 'الوصول للخزينة',
    'perm.MANAGE_SETTINGS': 'إعدادات النظام',
    'perm.MANAGE_USERS': 'إدارة المستخدمين',
    
    // Invoices & Sales
    'inv.add': 'إضافة صنف',
    'inv.add_product': 'إضافة منتج',
    'inv.customer': 'العميل',
    'inv.supplier': 'المورد',
    'inv.total': 'الإجمالي',
    'inv.subtotal': 'المجموع',
    'inv.discount': 'خصم',
    'inv.additional_discount': 'خصم إضافي',
    'inv.net_total': 'صافي الفاتورة',
    'inv.prev_balance': 'رصيد سابق',
    'inv.grand_total': 'المطلوب سداده',
    'inv.cash_paid': 'المدفوع نقداً',
    'inv.new_balance': 'رصيد حالي',
    'inv.processing': 'جاري المعالجة...',
    'inv.finalize': 'إنهاء الفاتورة',
    'inv.update': 'تحديث الفاتورة',
    'inv.save_print': 'حفظ وطباعة',
    'inv.product': 'الصنف',
    'inv.batch': 'تشغيلة',
    'inv.qty': 'الكمية',
    'inv.bonus': 'بونص',
    'inv.price': 'السعر',
    'inv.action': 'إجراء',
    'inv.empty_cart': 'السلة فارغة',
    'inv.select_customer': 'اختر العميل',
    'inv.select_product': 'اختر الصنف',
    'inv.select_batch': 'اختر التشغيلة',
    'inv.add_btn': 'إضافة',
    'inv.insufficient_stock': 'الرصيد لا يسمح',
    'inv.details': 'تفاصيل الفاتورة',
    'inv.select_warehouse': 'اختر المخزن',
    'inv.profit': 'الربح',
    'inv.security_warning': 'تنبيه أمني',
    'inv.below_cost_desc': 'أنت تحاول بيع صنف بسعر أقل من التكلفة. هذا الإجراء يتطلب موافقة المدير.',
    'inv.selling_net': 'سعر البيع (الصافي)',
    'inv.admin_pass_prompt': 'كلمة مرور المدير',
    'inv.approve': 'موافقة على البيع',
    'inv.wrong_pass': 'كلمة المرور غير صحيحة',
    'inv.return_mode': 'وضع المرتجع',
    'inv.returns_active': 'المرتجعات نشطة',
    'inv.sales_return': 'مرتجع مبيعات',
    'inv.total_items': 'عدد الأصناف',
    'inv.add_return_item': 'إضافة صنف مرتجع',
    'inv.manual_price': 'سعر يدوي',
    'inv.save_off_public': 'توفر {percent}% عن الجمهور',
    'inv.disc_percent': 'خصم %',
    'inv.return_summary': 'ملخص المرتجع',
    'inv.payment_summary': 'ملخص الدفع',
    'inv.cash_refunded': 'نقدية مستردة',
    'inv.process_return': 'تسجيل المرتجع',
    'inv.settings': 'إعدادات الفاتورة',
    'inv.standard_pricing': 'تسعير قياسي',
    'inv.standard_desc': 'سعر التشغيلة + خصم %',
    'inv.manual_price_only': 'سعر يدوي فقط',
    'inv.manual_desc': 'إدخال السعر يدوياً. بدون خصم.',
    'inv.profit_view': 'عرض الربحية',
    'inv.profit_desc': 'سعر يدوي + خصم. إظهار التكلفة وسعر الجمهور.',

    // Purchasing
    'pur.title': 'فاتورة مشتريات جديدة',
    'pur.return_title': 'مرتجع مشتريات',
    'pur.list_title': 'سجل المشتريات',
    'pur.select_supplier': 'اختر المورد',
    'pur.cost': 'سعر التكلفة',
    'pur.sell': 'سعر البيع',
    'pur.batch': 'رقم التشغيلة',
    'pur.expiry': 'تاريخ الصلاحية',
    'pur.add_item': 'إضافة بند',
    'pur.submit': 'حفظ المشتريات',
    'pur.return_submit': 'حفظ المرتجع',
    'pur.new_order': 'طلب شراء جديد',
    'pur.order_summary': 'ملخص الطلب',
    'pur.add_to_order': 'أضف أصناف للطلب',
    'pur.save_order_log': 'حفظ في السجل',
    'pur.items_count': 'عدد الأصناف',
    'pur.receive': 'استلام / مراجعة',
    'pur.review_order': 'مراجعة الطلب والاستلام',
    'pur.convert_invoice': 'تأكيد الاستلام وإنشاء فاتورة',
    'pur.convert_success': 'تم تحويل الطلب إلى فاتورة مشتريات بنجاح!',
    'pur.type': 'النوع',
    'pur.invoice_no': 'رقم الفاتورة',
    'pur.total_amount': 'الإجمالي',
    'pur.paid_amount': 'المدفوع',

    // Product
    'prod.new_title': 'إضافة صنف جديد',
    'prod.name': 'اسم الصنف',
    'prod.code': 'كود / باركود',
    'prod.pkg_type': 'نوع العبوة',
    'prod.pkg_items': 'العدد داخل العبوة',
    
    // Lists & Common
    'list.title': 'سجل المبيعات',
    'list.search': 'بحث برقم الفاتورة...',
    'list.status': 'الحالة',
    'list.view': 'عرض',
    'list.edit': 'تعديل',
    'list.no_data': 'لا توجد بيانات',
    'common.date': 'التاريخ',
    'common.customer': 'العميل',
    'common.user': 'المستخدم',
    'common.status': 'الحالة',
    'common.action': 'إجراء',
    'common.success_import': 'تم الاستيراد بنجاح',
    'common.error_excel': 'خطأ في قراءة الملف',
    'common.statement': 'كشف حساب',
    'common.debit': 'مدين',
    'common.credit': 'دائن',
    'common.balance': 'الرصيد',
    'common.desc': 'البيان',
    'common.opening': 'رصيد افتتاحي',
    'common.print': 'طباعة',
    'common.landscape': 'أفقي',
    'common.thermal': 'حراري',
    'common.close': 'إغلاق',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.show': 'عرض',
    'common.items': 'الأصناف',
    'status.paid': 'مدفوع',
    'status.partial': 'جزئي',
    'status.unpaid': 'غير مدفوع',
    
    // Reports
    'rep.period': 'الفترة الزمنية',
    'rep.from': 'من',
    'rep.to': 'إلى',
    'rep.apply': 'تطبيق الفلتر',
    'rep.today': 'اليوم',
    'rep.this_month': 'هذا الشهر',
    'rep.last_month': 'الشهر الماضي',
    'rep.this_year': 'هذه السنة',
    'rep.tab.financial': 'المالية (أرباح وخسائر)',
    'rep.tab.sales': 'تحليل المبيعات',
    'rep.tab.purchases': 'تحليل المشتريات',
    'rep.tab.inventory': 'قيمة المخزون',
    'rep.tab.partners': 'الشركاء والمديونيات',
    'rep.tab.reps': 'المندوبين',
    'rep.tab.telesales': 'تقارير التيليسيلز',
    'rep.tab.monthly': 'الملخص الشهري',
    'rep.tab.shortages': 'النواقص',
    'rep.gross_profit': 'مجمل الربح',
    'rep.net_profit': 'صافي الربح',
    'rep.total_revenue': 'إجمالي الإيرادات',
    'rep.cogs': 'تكلفة البضاعة المباعة',
    'rep.expenses': 'المصروفات التشغيلية',
    'rep.stock_value': 'قيمة الأصول المخزنية',
    'rep.receivables': 'المديونيات (لـنا عند العملاء)',
    'rep.payables': 'المستحقات (علينا للموردين)',
    'rep.area': 'المنطقة',
    'rep.all_customers': 'كل العملاء',
    'rep.all_areas': 'كل المناطق',
    'rep.product_breakdown': 'تفاصيل مبيعات الأصناف',
    'rep.units': 'وحدات',
    'rep.sales_volume': 'حجم المبيعات',
    'rep.invoice_count': 'عدد الفواتير',
    'rep.active_customers': 'العملاء النشطين',
    'rep.commission_est': 'عمولة تقديرية (1%)',
    'rep.all_reps': 'كل المندوبين',
    'rep.item_details': 'تفاصيل مبيعات الصنف',
    'rep.short.daily': 'نواقص المبيعات اليومية',
    'rep.short.general': 'نواقص عامة (أقل من المعدل)',
    'rep.short.stagnant': 'راكد (بدون مبيعات)',
    'rep.short.sold_today_list': 'مبيعات اليوم',
    'rep.short.best_selling': 'الأكثر مبيعاً',
    'rep.short.current': 'الرصيد الحالي',
    'rep.short.sold_today': 'مباع اليوم',
    'rep.short.total_sold': 'إجمالي المباع',
    'rep.short.status': 'الحالة',
    'rep.short.out_of_stock': 'نفذت الكمية',
    'rep.short.low_stock': 'رصيد منخفض',
    'rep.last_cost_1': 'آخر تكلفة 1',
    'rep.last_cost_2': 'آخر تكلفة 2',
    'rep.monthly_avg': 'معدل شهري',
    'rep.short.show_top': 'عرض أعلى',
    'rep.short.show_all': 'عرض الكل',
    'rep.agent': 'اسم المندوب/التيليسيلز',
    'rep.orders_count': 'عدد الأوردرات',
    'rep.total_value': 'إجمالي القيمة',
    'rep.details': 'التفاصيل',
    'rep.mon.sales': 'المبيعات',
    'rep.mon.cash': 'مقبوضات نقدية',
    'rep.mon.purchases': 'المشتريات',
    'rep.mon.expenses': 'المصروفات',
    'rep.mon.credit': 'الآجل (علي العملاء)',
    'rep.mon.select': 'اختر الشهر',
    
    // Analysis
    'analysis.title': 'تحليل المخزون المتقدم',
    'analysis.abc_title': 'تصنيف ABC (باريتو)',
    'analysis.valuation_title': 'التقييم ومتوسط التكلفة المرجح',
    'analysis.class_a': 'فئة A (عالي القيمة)',
    'analysis.class_b': 'فئة B (متوسط)',
    'analysis.class_c': 'فئة C (منخفض القيمة)',
    'analysis.wac': 'متوسط التكلفة المرجح',
    'analysis.total_asset': 'إجمالي قيمة الأصل',
    'analysis.turnover': 'معدل الدوران التقديري',
    'analysis.revenue_share': 'حصة الإيرادات',
    'analysis.optimize': 'تحسين مستويات المخزون باستخدام تصنيف ABC ومقاييس التقييم.',
    'analysis.latest_cost': 'أحدث تكلفة'
  }
};

export const t = (key: string): string => {
  const settings = db.getSettings();
  const lang = settings.language || 'en';
  // @ts-ignore
  return translations[lang]?.[key] || key;
};

export const isRTL = (): boolean => {
  const settings = db.getSettings();
  return settings.language === 'ar';
};